# Generated by Django 3.1.6 on 2021-03-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=100, unique=True)),
                ('caticonnm', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=100)),
                ('subcatnm', models.CharField(max_length=100, unique=True)),
                ('subcaticonnm', models.CharField(max_length=1000)),
            ],
        ),
    ]
