# Generated by Django 3.1.6 on 2021-03-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('bprice', models.IntegerField()),
                ('file1', models.CharField(max_length=100)),
                ('file2', models.CharField(max_length=100)),
                ('file3', models.CharField(max_length=100)),
                ('file4', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('uid', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
